# Generated by Django 5.1.1 on 2024-09-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Municipios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_ibge", models.IntegerField(null=True)),
                ("nome", models.CharField(max_length=255, null=True)),
                ("latitude", models.FloatField(null=True)),
                ("longitude", models.FloatField(null=True)),
                ("capital", models.IntegerField(null=True)),
                ("codigo_uf", models.IntegerField(null=True)),
                ("siafi_id", models.IntegerField(null=True)),
                ("ddd", models.IntegerField(null=True)),
                ("fuso_horario", models.CharField(max_length=50, null=True)),
            ],
            options={
                "db_table": "municipios_ibge",
            },
        ),
    ]
