# Generated by Django 5.1.1 on 2024-09-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Indeferido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpf", models.BigIntegerField(blank=True, null=True)),
                (
                    "nome_completo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("data_nascimento", models.DateField(blank=True, null=True)),
                ("data_indeferimento", models.DateField(blank=True, null=True)),
                ("especie_beneficio", models.IntegerField(blank=True, null=True)),
                (
                    "descricao_especie_beneficio",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "motivo_indeferimento",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("sexo", models.CharField(blank=True, max_length=20, null=True)),
                ("nome_mae", models.CharField(blank=True, max_length=255, null=True)),
                ("endereco", models.TextField(blank=True, null=True)),
                ("bairro", models.CharField(blank=True, max_length=255, null=True)),
                ("cep", models.CharField(blank=True, max_length=10, null=True)),
                ("municipio", models.CharField(blank=True, max_length=255, null=True)),
                ("uf", models.CharField(blank=True, max_length=2, null=True)),
                (
                    "competencia_indeferimento",
                    models.IntegerField(blank=True, null=True),
                ),
                ("ano_indeferimento", models.IntegerField(blank=True, null=True)),
                ("clientela", models.CharField(blank=True, max_length=255, null=True)),
                ("celular_1", models.CharField(blank=True, max_length=20, null=True)),
                ("resultado_celular_1", models.TextField(blank=True, null=True)),
                ("celular_2", models.CharField(blank=True, max_length=20, null=True)),
                ("resultado_celular_2", models.TextField(blank=True, null=True)),
                ("celular_3", models.CharField(blank=True, max_length=20, null=True)),
                ("resultado_celular_3", models.TextField(blank=True, null=True)),
                ("celular_4", models.CharField(blank=True, max_length=20, null=True)),
                ("resultado_celular_4", models.TextField(blank=True, null=True)),
                ("fixo_1", models.CharField(blank=True, max_length=20, null=True)),
                ("resultado_fixo_1", models.TextField(blank=True, null=True)),
                ("fixo_2", models.CharField(blank=True, max_length=20, null=True)),
                ("resultado_fixo_2", models.TextField(blank=True, null=True)),
                ("fixo_3", models.CharField(blank=True, max_length=20, null=True)),
                ("resultado_fixo_3", models.TextField(blank=True, null=True)),
                ("fixo_4", models.CharField(blank=True, max_length=20, null=True)),
                ("resultado_fixo_4", models.TextField(blank=True, null=True)),
                ("email_1", models.EmailField(blank=True, max_length=254, null=True)),
                ("email_2", models.EmailField(blank=True, max_length=254, null=True)),
                ("email_3", models.EmailField(blank=True, max_length=254, null=True)),
                ("email_4", models.EmailField(blank=True, max_length=254, null=True)),
                ("resultado_geral_contato", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "pf_indeferidos",
            },
        ),
    ]
