# Generated by Django 5.1.1 on 2024-09-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indeferidos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndeferidosDone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpf", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "indeferidos_done",
            },
        ),
        migrations.RenameModel(
            old_name="Indeferido",
            new_name="Indeferidos",
        ),
    ]
